[project]
name = "semantic-veritas-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jonathan Belden", email = "belden@oakleasimpsonsecurity.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
semantic-veritas-tool = "semantic_veritas_tool:main"

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"
